steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/iot-sensor-api:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iot-sensor-api:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iot-sensor-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iot-sensor-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--set-env-vars'
      - 'MQTT_BROKER=wdfcc162.ala.dedicated.gcp.emqxcloud.com,MQTT_PORT=1883,MQTT_USER=pc-01,MQTT_PASSWORD=123AcE,MQTT_TOPIC=device01/sensors,MQTT_CLIENT_ID=iot-backend-api'

images:
  - 'gcr.io/$PROJECT_ID/iot-sensor-api:latest'
